### ISSUE TITLE
readOnly or enabled property

### ISSUE THREAD

**Issue by tonagy** [Mindinventory/slider_controller#1]
I'm using this package and i need a readOnly or enabled. For this solution i call onChange: () => null, but sometimes detect mi horizontaDrag and change the color of the RatingBox. Could be better to update the package for a enabled or readOnly? or another solution?

This video it's a comparation between a null and changed , the null shouldn't show the active bar Color.

https://user-images.githubusercontent.com/106313333/176152789-72b376d7-3e58-454a-9bac-b0db8c0ba6d0.mp4

**Comment by mohit-chauhan-mi** [comment]
@tonagy - We've added **isDraggable** flag to Enable or Disable Drag Gesture of the Slider. Please check it in the new version of the package. Thank you.

**Comment by tonagy** [comment]
Thanks a lot for the update and the reply.
