### ISSUE TITLE
How do I set the divisions?

### ISSUE THREAD

**Issue by sunjianan9900** [Mindinventory/slider_controller#2]
The components are very beautiful 
How do I set the divisions?

**Comment by deep-mindinventory** [comment]
@sunjianan9900 can you please elaborate more on this issue?

**Comment by sunjianan9900** [comment]
> @sunjianan9900 can you please elaborate more on this issue?

![image](https://user-images.githubusercontent.com/10936316/191955511-f2462cba-061a-42cc-bd79-11984288c842.png)
change  toStringAsFixed(1) To toStringAsFixed(3) Can solve my problem
