### ISSUE TITLE
vertical layout

### ISSUE THREAD

**Issue by itMcdull** [Mindinventory/slider_controller#4]
Thank you for your package, can you support vertical arrangement

**Comment by mohit-chauhan-mi** [comment]
@itMcdull What do you mean by **vertical layout**, can you please elaborate more

**Comment by mohit-chauhan-mi** [comment]
@itMcdull You may use the RotatedBox widget above the SliderController widget to achieve like this,

![Simulator Screen Shot - iPhone 11 Pro - 2023-03-29 at 17 44 11](https://user-images.githubusercontent.com/71555515/228532337-f9e2496b-acb1-4467-be02-c28d43f9a6b5.png)

closing this now, reopen it if you need more details.
